### ISSUE TITLE
Cloudflare

### ISSUE THREAD

**Issue by fibodevy** [delphius/fpmtls#1]
Good job. Kind of working. I like if something is implemented from scrach without using 3rd party shared libs.

It currenlty (checked on few websites) doesnt work with Cloudflare certificates, is it known issue? Imho you should try to add support for this, many many websites uses CF certificates.

**Comment by delphius** [comment]
> Good job. Kind of working. I like if something is implemented from scrach without using 3rd party shared libs.

Thanks! To begin with, I want to turn this Frankenstein, assembled from completely different parts (since the direct adaptation from python as expected did not work), into a simple and understandable code, which at the moment is understandable only to me.

> It currenlty (checked on few websites) doesnt work with Cloudflare certificates, is it known issue? Imho you should try to add support for this, many many websites uses CF certificates.

Taking into account the fact that the certificate verification is simply skipped, it does not work with certificates in any way at all, the site google.com also does not open and the stop is also on certificates, most likely this is due to the implemented work of the protocol in deviation from RFC8446 (or with flaws) and it is necessary to finish it (since the original code has exactly the same problem). It is possible that on some sites certificates come in one message, not two (the chain in the first, the server in the second), so you can try to skip the second message (do not forget to remove the counter). https://github.com/delphius/fpmtls/blob/efd58e9f5de060bf56cfe0f790275f0b9bfb2e64/fptls.pas#L1193
But I haven't figured it out yet

P.S. ~I forgot about SNI, if we don't say in hello the server domain name, then server will don't know, what certificate to send us and stucked. I think thats it.~ Add it, problem doesn't slove.

But the entire chain of certificates, including the server one, is obtained and decrypted, so that no one interferes with the implementation of verification using already created fpc modules for working with certificates.

At the moment, I see my task in creating a working stub that allows you to download any data over https, for those cases where security is absolutely not important, while there is simply no other way to do this except to use https, and for this you don't want to pull dependencies like openssl or openssl + indy/synapse/etc. At the same time, strictly following all the requirements of the protocol, but without taking into account authentication and secure implementation of algorithms for side channel attacks

In addition, the standard fpc modules have p-256, HKDF and a few other interesting things that will cut the code in half, in addition to refactoring, the goal is to fit in 500 lines of code.
And I wrote all this with my hands in order to understand and feel each cryptoprimitive myself, otherwise there would not be a complete understanding of how and why it works, the functions built into fpc relax in this regard, causing unwillingness to watch their code, it works and it's okay))))

**Comment by fibodevy** [comment]
> the goal is to fit in 500 lines of code.

If you think to remove some of your functions and replace them with others already made, I would suggest the opposite 😀

Do as much code as possible from scratch. Your current uses sections is ok, binary output size is acceptable, but if you add some custom code it will quickly grow up to several megabytes, dont even add "Classes" there. Some would use TMemoryStreams and the like, you did it with TBytes which is just array of byte, and thats great.

Keep the binary output small, let the code grow.

> which at the moment is understandable only to me.

Not only, Its pretty readable and self explainable

**Comment by delphius** [comment]
> Do as much code as possible from scratch. Your current uses sections is ok

Its all I need is already in uses, no more dependencies.

> dont even add "Classes" there

No, just like sockets and ssockets, plain module and higher level abstraction above it in the future if it needs. But many structures ask to be grouped into records as minimum)


> Keep the binary output small, let the code grow.

No need to duplicate code if it will not lead to dependencies and binary grow, especially if its in fpc standard units and looks good.

> Its pretty readable and self explainable

There is no limit to perfection, but there is always reasonable sufficiency)

A mandatory question is the inclusion of chacha20+poly1305, without them it will not be an implementation, but a profanation

**Comment by delphius** [comment]
> It currenlty (checked on few websites) doesnt work with Cloudflare certificates, is it known issue?

Still, as I suggested at the beginning, the problem with google, as with some other sites, is that they send the encrypted extensions message immediately along with server certificates + cert_verify + server finished, and not sequentially with separate messages, so the implementation stops. I will be able to fix it only closer to the weekend, while there is no time

To check it out, just comment out from
https://github.com/delphius/fpmtls/blob/5209c3eb6c94f42ab1690f7e9f13a0ab4fb1ad80/fptls.pas#L1198
to
https://github.com/delphius/fpmtls/blob/5209c3eb6c94f42ab1690f7e9f13a0ab4fb1ad80/fptls.pas#L1220

**Comment by delphius** [comment]
> It currenlty (checked on few websites) doesnt work with Cloudflare certificates

I'll try to fix it, could you give some examples of sites that don't work?

**Comment by fibodevy** [comment]
Check if domain NSes are *.ns.cloudflare.com, high chance for a hit

- gitlab.com
- envato.com
- codepen.io

EDIT: Actually these websites can use their own certs so nvm, I will give you some examples in 1 to 2 hours, busy now

EDIT2: Ok, I checked and these sites use CF certs and none of them works in `fpmtls`

**Comment by delphius** [comment]
> Ok, I checked and these sites use CF certs and none of them works in `fpmtls`

It was not about certs issue, but about protocol implementation. Now you can check it.

**Comment by fibodevy** [comment]
Most sites now work, even most of my little sites behind cloudflare, except for one. I can't publish the address, sorry. I'll check some more sites using CF later.

```
--------------------
Receiving and derypt message
--------------------
<--Recive TLS
Record Type: TLS_APPLICATION_DATA (0x17)
Record Length: 19 (0x0013)
Record Content: 9D18B5684B7283A3E9C6A3B3D91323451E2683
--------------------
Record Type: TLS_ALERT (0x15)
Decrypted message length: 2, parsing messages...
--------------------
```

```
Project project1 raised exception class 'Exception' with message:
Parsing Unknown message: (0x02)

In file 'project1.lpr' at line 1294
```

From debugger, contents of msg:
```
decrypted_msg = Len=2: (2,40)
```

If this message (server hello) is ignored, then: Server terminated the connection

**Comment by delphius** [comment]
> Receiving and derypt message

It is necessary to understand more specifically what the reason is and what kind of error comes out...this is not a full-fledged implementation of the protocol, but just a direct implementation of a specific configuration, not universal at all

In order to practically attach the protocol, I screwed it to sending mail messages, if there is an opportunity to test, I will be grateful.

https://github.com/delphius/fpmailsend

https://github.com/delphius/fpmailsend/tree/main/native/tlsmail

gmail (smtps 465) works well, and some national rus servers too...

**Comment by delphius** [comment]
> If this message (server hello) is ignored

We cant ignore it, cause its about connection parameters negotiation. May be server realization dont support tsl 1.3 or exactly parameters which script implements.

In this case it throw alert message x0228 (x02 - fatal, x28 (40) - TLS negotiation failure)
